### ISSUE TITLE
Can ParallaxViewContainer be draggable?

### ISSUE THREAD

**Issue by thidayatullah** [peterpaulis/M6UniversalParallaxViewController#4]
So basically I want the whole area scrollable.  Currently we can only scroll the tableview area below the ParallaxView.  How can I make it so the parallaxView scrollable as same as the tableview?

**Comment by peterpaulis** [comment]
Hi, iam currently working on an app where i will need to do the same, so an updated version will be available in 1 - 2 weeks

I also fixed some other issues relating to section headers

Basically you will need to add a gesture recognizer to the parallax view and onhad of this scroll the table

**Comment by thidayatullah** [comment]
Yeah, I've been playing with that too.

I added a UIPanGestureRecognizer to the parallax view and trying to change the table contentoffset when user pan it.  The problem is that `CGPoint translation = [recognizer translationInView:self.view];` only return a small value like 0.5 or -0.5.  So the table view doesn't scroll noticeably.

So I will be very grateful when you come up with a solution. (:

Huge thanks for you anyway.

**Comment by peterpaulis** [comment]
Hi
pls see the latest code and sample
https://github.com/peterpaulis/M6UniversalParallaxViewController
