### ISSUE TITLE
Sections with custom UIView won't scroll

### ISSUE THREAD

**Issue by tobatha** [peterpaulis/M6UniversalParallaxViewController#5]
Yo, Pete
       Great parallax VC, and super easy to config with xib specially.
       Right now it seems to be having this very problem that, if you call the api in UITableViewDelelgate
       - (UIView *)tableView:(UITableView *)tableView viewForHeaderInSection:(NSInteger)section
       
       The custom section is initialized, but when scrolling the table, the section view stays still
       I have no idea if i'm doing sth wrong so as to cause the problem or other condition, lemme know

       Thanks in advance.

**Comment by peterpaulis** [comment]
Hi

I already did solve this and will release an update :)

Temporary you can subclass the uitablevie as described in readme




On Thursday, February 5, 2015, tobatha <notifications@github.com> wrote:

> Yo, Pete
> Great parallax VC, and super easy to config with xib specially.
> Right now it seems to be having this very problem that, if you call the
> api in UITableViewDelelgate
> - (UIView *)tableView:(UITableView *)tableView
> viewForHeaderInSection:(NSInteger)section
>
>    The custom section is initialized, but when scrolling the table, the section view stays still
>    I have no idea if i'm doing sth wrong so as to cause the problem or other condition, lemme know
>
>    Thanks in advance.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/peterpaulis/M6UniversalParallaxViewController/issues/5>
> .
>


-- 
Prajem príjemný deň...
Mgr. Peter Paulis

**Comment by tobatha** [comment]
Hi Pete,
i did subclass the tableview in storyboard to M6HeaderInsetTableView like in the demo project, but the custom section view will stay at the originated position and functions like normal table view does, as if the the table view's height is not growing when scrolling up
![parallaxbug](https://cloud.githubusercontent.com/assets/2382153/6057409/0bf8e1e6-ad59-11e4-818b-5892ec94bf8c.png)

**Comment by peterpaulis** [comment]
Hi, pls see the latest code just pushed https://github.com/peterpaulis/M6UniversalParallaxViewController
